version: '3.8'

services:
  # Redis Stack (Redis + RedisInsight)
  redis:
    image: redis/redis-stack:latest
    container_name: ai-tutor-redis
    ports:
      - "6379:6379"  # Redis
      - "8001:8001"  # RedisInsight
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD:-password}
    networks:
      - app-network
    restart: unless-stopped

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-tutor-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
      - DEBUG=true
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: